default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5

development:
  <<: *default
  database: farmer_development
  host: 192.168.99.100
  port: 32769
  username: postgres
  password: postgres

test:
  <<: *default
  database: farmer_test
  host: 192.168.99.100
  port: 32769
  username: postgres
  password: postgres

production:
  <<: *default
  database: farmer_production
  host: 192.168.99.100
  port: 32769
  username: postgres
  password: postgres
