development:
  adapter: postgresql
  encoding: unicode
  pool: 5
  database: farmer_development
  host: 192.168.99.100
  port: 32769
  username: postgres
  password: postgres
production:
  adapter: postgresql
  encoding: unicode
  pool: 5
  database: farmer_production
  host: <%= ENV["SQL_HOST"] %>
  port: <%= ENV["SQL_PORT"] %>
  username: <%= ENV["SQL_USERNAME"] %>
  password: <%= ENV["SQL_PASSWORD"] %>
